export const recapFonts = {
  BMKkubulim: require("../../../assets/fonts/BMKkubulim.otf"),
  BookkGothicBold: require("../../../assets/fonts/BookkGothic_Bold.ttf"),
  BookkGothicLight: require("../../../assets/fonts/BookkGothic_Light.ttf"),
  BookkMyungjoBold: require("../../../assets/fonts/BookkMyungjo_Bold.ttf"),
  BookkMyungjoLight: require("../../../assets/fonts/BookkMyungjo_Light.ttf"),
  ChosunCentennial: require("../../../assets/fonts/ChosunCentennial_otf.otf"),
  ChosunGu: require("../../../assets/fonts/ChosunGu.ttf"),
  ChosunNm: require("../../../assets/fonts/ChosunNm.ttf"),
  GmarketSansBold: require("../../../assets/fonts/GmarketSans-Bold.otf"),
  GmarketSansLight: require("../../../assets/fonts/GmarketSans-Light.otf"),
  GmarketSansRegular: require("../../../assets/fonts/GmarketSans-Regular.otf"),
  GriunFromsol: require("../../../assets/fonts/Griun_Fromsol-Rg.ttf"),
  GriunXHangeulOchungiKim: require("../../../assets/fonts/GriunXHangeul_OCHUNGI.KIM-Rg.ttf"),
  Isayoon: require("../../../assets/fonts/이서윤체.ttf"),
  Jalnan2: require("../../../assets/fonts/Jalnan2.otf"),
  Jejudoldam: require("../../../assets/fonts/jejudoldam.otf"),
  KimWildgagBold: require("../../../assets/fonts/[KIM]WILDgag-Bold.ttf"),
  MaruBuriBold: require("../../../assets/fonts/MaruBuri-Bold.otf"),
  MaruBuriLight: require("../../../assets/fonts/MaruBuri-Light.otf"),
  MaruBuriRegular: require("../../../assets/fonts/MaruBuri-Regular.otf"),
  Mona12Bold: require("../../../assets/fonts/Mona12-Bold.otf"),
  Mona12Regular: require("../../../assets/fonts/Mona12-Regular.otf"),
  OngleapParkDahyun: require("../../../assets/fonts/온글잎 박다현체.ttf"),
  PaperlogyBold: require("../../../assets/fonts/Paperlogy-Bold.ttf"),
  PaperlogyLight: require("../../../assets/fonts/Paperlogy-Light.ttf"),
  PaperlogyRegular: require("../../../assets/fonts/Paperlogy-Regular.ttf"),
  PretendardBold: require("../../../assets/fonts/Pretendard-Bold.otf"),
  PretendardLight: require("../../../assets/fonts/Pretendard-Light.otf"),
  PretendardRegular: require("../../../assets/fonts/Pretendard-Regular.otf"),
  YoonChildfundkoreaManSeh: require("../../../assets/fonts/YoonChildfundkoreaManSeh.otf"),
} as const;

export type { RecapTextFontFamily as RecapFontFamily } from "@/shared/recap/recap-font-families";
